language: go

env:
  - CODECOV_TOKEN="6280c29e-7042-4458-bfbd-be102bda6029"

install:
  - go get ./...

script: 
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

